CREATE TABLE youtubeProjectDB.captions(
	videoId VARCHAR(15) NOT NULL,
	captionsText TEXT,
	captionsFile TEXT,
	language VARCHAR(5),
	captionsFileFormat VARCHAR(5),
	queryMethod VARCHAR(150), 
	queriedAt VARCHAR(30),
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
 );

ALTER TABLE youtubeProjectDB.captions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

# DataError: (1406, "Data too long for column 'captionsXML' at row 1")
# Kind of error message you want
# No..
# Was generated by https://www.youtube.com/watch?v=XZOUPnH4aN0
# Which is just full of spam!

# 31.03.2017 - look what happened!
# DataError: (1406, "Data too long for column 'language' at row 1")
# 'zh-Hant' was te offending language, 7 characters long, 2 too many.


ALTER TABLE youtubeProjectDB.captions MODIFY language VARCHAR(15)

# that was not enough..
#  Oops! <class 'pymysql.err.DataError'> insertion error occured with videoId uzsoBzPFEEQ
# Yes, this religious guy is talking for over an hour about getting rid of demons..
# a = getVtt(PATH+file) 
# b = readFile(PATH+file)
# len(a)  72341
# len(b) 102874
# http://stackoverflow.com/questions/6766781/maximum-length-for-mysql-type-text
# L is the number of bytes in your text field. 
# So the maximmum number of chars for text is 216-1 (using single-byte characters). 
# Means 65 535 chars(using single-byte characters).

# ...and 72341 > 65 535
# That came from a guy ranting and raving for just a bit more than an hour. 
# I shoud think that my text column should take at least 2-3 hours before it 
# truncates or generates an error hence the following is justified:

ALTER TABLE youtubeProjectDB.captions MODIFY captionsFile MEDIUMTEXT;
ALTER TABLE youtubeProjectDB.captions MODIFY captionsText MEDIUMTEXT;

 